# Download book {#download-book}

If you liked the book and wanted to support the project, you can acquire forever and ever the portable **Data Science Live Book** in PDF, mobi, and Kindle version. The three together! `r emo::ji("slightly_smiling_face")`. 

<br> 

Secure purchase by **Gumroad** `r emo::ji("closed_lock_with_key")`:

---

<script src="https://gumroad.com/js/gumroad-embed.js"></script>
<div class="gumroad-product-embed" data-gumroad-product-id="tORBv"><a href="https://gumroad.com/l/tORBv">Loading...</a></div>

---

In case you want to buy it directly from the Gumroad site, follow this link: https://gumroad.com/l/tORBv

---

_Is there any difference between the on-line and the PDF, mobi or Kindle versions?_

No, they are the same. The Data Science Live Book is and will always be fully accessible, actually it's open source  (`Attribution-NonCommercial-ShareAlike 4.0 International`).

_What happen if a new version is released? / Can I access newer versions?_

Sure! After the purchase, from time to time you'll be notified via email about a newer version, (you can opt-out about this notification).

The modality is name-your-price, with a minimum of 5 US dollar. Happy reading! `r emo::ji("rocket")`

_How can I contact you?_

If you wish to contact me you can do so at pcasas.biz <at> gmail.com, you don’t need an specific reason anything from suggesting a new topic to just sharing a good experience after applying concepts you learnt here are welcome!

`r emo::ji("worried")`: _I don’t have enough money to contribute, but I still *really* want the portable version._
No worries, we all have rough times, just contact me at pcasas.biz (at) gmail.com `r emo::ji("wink")`.

I like the idea of having -when possible- free access to education, such is the case of college education in Argentina, Finland (among others few countries). So anyone who wants to study and explore new horizons can do it. Money shouldn't be a barrier to acquiring knowledge. 



**So what's next?!**

The following releases will be more focus on the creation of the predictive model itslef, rather than the data preparation stage which is already covered in the book.

The other point will be creating short case studies, or well, a sort of summary of current book content. Putting in a few pages several approaches from different parts of the book.

Stay tuned at [twitter](https://twitter.com/pabloc_ds).



