```{r ,results="hide", echo=FALSE}
library(knitr)
knitr::opts_chunk$set(out.width="400px", dpi=120)
knitr::opts_knit$set(base.dir = "download_pdf_ebook")
``` 

Download PDF and eBook
===


If you liked the book and want to support the project, you can adquire forever and ever the portable Data Science Live Book version in both formats, PDF and eBook. 

<br> 

**FAQ**

* _Is there any difference between the on-line and the PDF/eBook version?_

No, they are the same. The Data Science Live Book is and will always be fully accessible, actually it's open source. Take an screenshot! 📸 

* _What happen if a new version is released?_

When you get your first copy, you can download newer versions.  You can be notify via email to get the new download link.

* _How can I contact you?_

If you want to say hello, contribute by telling that some part is not well explained, suggest a new topic drop me an email at: pcasas.biz at gmail.com

Also, if now the economics times don't go so well and you _need_ the portable version anyway, just let me know.

I like the idea of -when possible- having free education material so anyone who wants to study and explore new horizons will can do it. I learnt **a lot** of things 
this way. Argentina, the country I live, is one of the few countries in having free education, kinder garden, high school and university.  

